apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: visbets-api
spec:
  template:
    spec:
      containers:
        - image: gcr.io/PROJECT_ID/visbets-api
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
          env:
            - name: ENVIRONMENT
              value: "production"
            - name: NBA_API_KEY
              valueFrom:
                secretKeyRef:
                  name: nba-api-key
                  key: api-key
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20 